version: "3"
services: 
    mymongo_1:
        image: "mongo"
        ports:
            - "27017:27017"
        networks:
            - pokemon-service
    
    images-server:
        build: .
        depends_on: 
            - mymongo_1
        ports:
            - "5002:5002"
        networks:
            - pokemon-service

networks:
    pokemon-service:
        external: true