version: "3"
services: 
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        networks:
            - pokemon-service
    
    pokemon-gateway:
        build: .
        depends_on: 
            - redis
        ports:
            - "5000:5000"
        networks:
            - pokemon-service

networks:
    pokemon-service:
        external: true